# Control file for continuous integration testing at http://travis-ci.org/

# ignore release tags
branches:
  except:
    /^RAIntegration.\d+\.\d+(\.\d+)?(-\S*)?$/  

language: cpp


jobs:
  include:
    - name: "Win32 Analysis"
      os: windows
      install:
        # CppUnitTestFramework, atlbase.h, afxres.h
        - choco install visualstudio2019community --package-parameters "--add Microsoft.VisualStudio.Component.VC.ATLMFC"
        # Microsoft.Cpp.Default.props
        - choco install visualstudio2019-workload-vctools
        # atlbase.h
        - choco install visualstudio2019-workload-nativedesktop
      script: ./BuildAll.bat Analysis x86

    - name: "Win64 Analysis"
      os: windows
      install:
        # CppUnitTestFramework, atlbase.h, afxres.h
        - choco install visualstudio2019community --package-parameters "--add Microsoft.VisualStudio.Component.VC.ATLMFC"
        # Microsoft.Cpp.Default.props, atlbase.h
        - choco install visualstudio2019-workload-nativedesktop
      script: ./BuildAll.bat Analysis x64
