# Control file for continuous integration testing at http://travis-ci.org/

# ignore release tags
branches:
  except:
    /^RAIntegration.\d+\.\d+(\.\d+)?(-\S*)?$/  

language: cpp


jobs:
  include:
    - name: "Win32 DLL"
      os: windows
      # builds with visualstudio2017buildtools - supports v141_xp target
      script: ./BuildAll.bat Release x86

    - name: "Win64 DLL"
      os: windows
      # builds with visualstudio2017buildtools - supports v141_xp target
      script: ./BuildAll.bat Release x64
    
    - name: "Win32 Tests"
      os: windows
      install:
        - choco install visualstudio2019community                  # CppUnitTestFramework
        - choco install visualstudio2019buildtools
        - choco install visualstudio2019-workload-vctools
        - choco install visualstudio2019-workload-nativedesktop    # atlbase.h
      # builds with visualstudio2019buildtools - does not support v141_xp target - uses v142 instead
      script: ./BuildAll.bat Tests x86

    - name: "Win64 Tests"
      os: windows
      install:
        - choco install visualstudio2019community                  # CppUnitTestFramework
        - choco install visualstudio2019buildtools
        - choco install visualstudio2019-workload-nativedesktop    # atlbase.h
      # builds with visualstudio2019buildtools - does not support v141_xp target - uses v142 instead
      script: ./BuildAll.bat Tests x64

    - name: "Win32 Analysis"
      os: windows
      install:
        - choco install visualstudio2019community                  # CppUnitTestFramework, atlbase.h
        - choco install visualstudio2019buildtools
        - choco install visualstudio2019-workload-vctools
        - choco install visualstudio2019-workload-nativedesktop    # atlbase.h
      # builds with visualstudio2019buildtools - does not support v141_xp target - uses v142 instead
      script: ./BuildAll.bat Analysis x86

    - name: "Win64 Analysis"
      os: windows
      script: ./BuildAll.bat Analysis x64
